/**
 * Catálogo origem → destino e tabelas esperadas no target.
 * Nomes de origem alinhados a entityTableMap / migrations reais.
 */

/** Contagens ANTES×DEPOIS (source → target) */
export const COUNT_PAIRS = [
  { source: 'ind_lista_usuarios', target: 'usuarios' },
  { source: 't_clientes', target: 'clientes' },
  { source: 't_produtos', target: 'produtos' },
  { source: 't_operadores', target: 'operadores' },
  { source: 't_etiqueta_configs', target: 'etiqueta_configs' },
  { source: 't_isotanques', target: 'isotanques' },
  { source: 't_descontaminacoes', target: 'descontaminacoes' },
  { source: 't_elementos_filtrantes', target: 'elementos_filtrantes' },
  { source: 't_entradas', target: 'entradas' },
  { source: 't_estoque', target: 'estoque' },
  { source: 't_transbordos', target: 'transbordos' },
  { source: 't_vasilhames', target: 'vasilhames' },
  { source: 't_filtracoes', target: 'filtracoes' },
  { source: 't_material_reservas', target: 'material_reservas' },
  { source: 't_saidas', target: 'saidas' },
  { source: 't_saida_leituras', target: 'saida_leituras' },
  { source: 't_transbordo_validacoes', target: 'transbordo_validacoes' },
  { source: 't_agendamentos_carregamento', target: 'agendamentos_carregamento' },
  { source: 't_validacao_leituras', target: 'validacao_leituras' },
  { source: 'perfis', target: 'perfis' },
  { source: 'perfil_permissoes', target: 'perfil_permissoes' },
  { source: 'usuario_permissoes', target: 'usuario_permissoes' },
  { source: 'ind_lista_receitas', target: 'receitas' },
  { source: 'ind_lista_pedidos', target: 'pedidos' },
  { source: 'ind_lista_producoes', target: 'producoes' },
  { source: 'ind_estoque_mp', target: 'estoque_mp' },
  { source: 'ind_lista_ensaios', target: 'ensaios' },
  { source: 'ind_cq_esp_tec', target: 'cq_especificacoes' },
  { source: 'ind_lista_equipamentoslab', target: 'equipamentos_lab' },
  { source: 'ind_cadastro_tanka', target: 'tanques_ind' },
  { source: 'ind_lista_inventario', target: 'inventarios_mp' },
  { source: 'ind_retornos_perdas', target: 'movimentos_mp' },
  { source: 'ind_transbordo_ind', target: 'transferencias_ind' },
  { source: 'ind_programacao_demanda', target: 'programacao_demanda' },
  { source: 'ind_lista_vasilhames', target: 'vasilhames_producao' },
  { source: 'ind_composicao_vasilhame', target: 'composicao_vasilhame_producao' },
  { source: 'ind_checklist_op', target: 'checklist_producao' },
  { source: 'ind_cq_resultados', target: 'cq_resultados' },
  { source: 'ind_validacoes', target: 'validacoes_mp' },
];

/** Tabelas que o schema v2 deve ter (≈46) */
export const EXPECTED_TARGET_TABLES = [
  'modulos',
  'perfis',
  'perfil_permissoes',
  'perfil_auditoria',
  'perfil_modulos',
  'usuarios',
  'sessions',
  'permissoes',
  'usuario_permissoes',
  'rate_limit_attempts',
  'rate_limit_logs',
  'clientes',
  'operadores',
  'etiqueta_configs',
  'produtos',
  'isotanques',
  'descontaminacoes',
  'elementos_filtrantes',
  'entradas',
  'estoque',
  'transbordos',
  'vasilhames',
  'filtracoes',
  'material_reservas',
  'transbordo_validacoes',
  'saidas',
  'saida_leituras',
  'agendamentos_carregamento',
  'validacao_leituras',
  'receitas',
  'pedidos',
  'producoes',
  'estoque_mp',
  'movimentos_mp',
  'tanques_ind',
  'transferencias_ind',
  'vasilhames_producao',
  'composicao_vasilhame_producao',
  'checklist_producao',
  'cq_resultados',
  'cq_especificacoes',
  'ensaios',
  'inventarios_mp',
  'equipamentos_lab',
  'programacao_demanda',
  'validacoes_mp',
];
